import Header from "@/components/Header";
import "../styles/global.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import PromptInput from "@/components/PromptInput";
import ClientProvider from "@/components/ClientProvider";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "AI art gallery",
  description: "Generated by skilled sparrow",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ClientProvider>
          {/* {Header} */}
          <Header />
          <PromptInput />
          {/* {Footer} */}
          {children}
        </ClientProvider>
      </body>
    </html>
  );
}
